
package name.subroutine.jardb.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ws", targetNamespace = "http://subroutine.name/jardb")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ws {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<name.subroutine.jardb.wsclient.Entry>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://subroutine.name/jardb", className = "name.subroutine.jardb.wsclient.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://subroutine.name/jardb", className = "name.subroutine.jardb.wsclient.SearchResponse")
    @Action(input = "http://subroutine.name/jardb/ws/searchRequest", output = "http://subroutine.name/jardb/ws/searchResponse")
    public List<Entry> search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://subroutine.name/jardb", className = "name.subroutine.jardb.wsclient.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://subroutine.name/jardb", className = "name.subroutine.jardb.wsclient.GetVersionResponse")
    @Action(input = "http://subroutine.name/jardb/ws/getVersionRequest", output = "http://subroutine.name/jardb/ws/getVersionResponse")
    public String getVersion();

}
