
package name.subroutine.jardb.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws", targetNamespace = "http://subroutine.name/jardb")
public class WsService
    extends Service
{

    private final static URL WS_WSDL_LOCATION;
    private final static WebServiceException WS_EXCEPTION;
    private final static QName WS_QNAME = new QName("http://subroutine.name/jardb", "ws");

    static {
        URL url = null;
        WebServiceException e = null;
        WS_WSDL_LOCATION = WsService.class.getClassLoader().getResource("META-INF/jardb.wsdl");
        WS_EXCEPTION = e;
    }

    public WsService() {
        super(__getWsdlLocation(), WS_QNAME);
    }

    public WsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS_QNAME, features);
    }

    public WsService(URL wsdlLocation) {
        super(wsdlLocation, WS_QNAME);
    }

    public WsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS_QNAME, features);
    }

    public WsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "wsPort")
    public Ws getWsPort() {
        return super.getPort(new QName("http://subroutine.name/jardb", "wsPort"), Ws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "wsPort")
    public Ws getWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://subroutine.name/jardb", "wsPort"), Ws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS_EXCEPTION!= null) {
            throw WS_EXCEPTION;
        }
        return WS_WSDL_LOCATION;
    }

}
